<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChamCongSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cham_cong')->insert([
            [
                'nguoi_dung_id' => 1,
                'ngay_cham_cong' => '2024-03-01',
                'gio_vao' => '08:00:00',
                'gio_ra' => '17:00:00',
                'so_gio_lam' => 8,
                'so_cong' => 1,
                'gio_tang_ca' => 0,
                'phut_di_muon' => 0,
                'phut_ve_som' => 0,
                'trang_thai' => 'dung_gio',
                'dia_chi_ip' => '192.168.1.100',
                'ten_wifi' => 'Company_WiFi',
                'dia_chi_mac' => 'AA:BB:CC:DD:EE:FF',
                'ten_thiet_bi' => 'PC-Admin',
                'phuong_thuc_cham_cong' => 'wifi',
                'ghi_chu' => null,
                'nguoi_phe_duyet_id' => 1,
                'trang_thai_duyet' => 1,
                'ghi_chu_duyet' => 'OK',
                'thoi_gian_phe_duyet' => '2024-03-01 17:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nguoi_dung_id' => 2,
                'ngay_cham_cong' => '2024-03-01',
                'gio_vao' => '08:15:00',
                'gio_ra' => '17:00:00',
                'so_gio_lam' => 7.75,
                'so_cong' => 0.97,
                'gio_tang_ca' => 0,
                'phut_di_muon' => 15,
                'phut_ve_som' => 0,
                'trang_thai' => 'di_muon',
                'dia_chi_ip' => '192.168.1.101',
                'ten_wifi' => 'Company_WiFi',
                'dia_chi_mac' => 'AA:BB:CC:DD:EE:01',
                'ten_thiet_bi' => 'PC-TruongPhong',
                'phuong_thuc_cham_cong' => 'ip',
                'ghi_chu' => 'Kẹt xe',
                'nguoi_phe_duyet_id' => 1,
                'trang_thai_duyet' => 1,
                'ghi_chu_duyet' => 'Đã duyệt',
                'thoi_gian_phe_duyet' => '2024-03-01 17:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nguoi_dung_id' => 3,
                'ngay_cham_cong' => '2024-03-01',
                'gio_vao' => '08:00:00',
                'gio_ra' => '16:45:00',
                'so_gio_lam' => 7.75,
                'so_cong' => 0.97,
                'gio_tang_ca' => 0,
                'phut_di_muon' => 0,
                'phut_ve_som' => 15,
                'trang_thai' => 've_som',
                'dia_chi_ip' => '192.168.1.102',
                'ten_wifi' => 'Company_WiFi',
                'dia_chi_mac' => 'AA:BB:CC:DD:EE:02',
                'ten_thiet_bi' => 'Laptop-NV1',
                'phuong_thuc_cham_cong' => 'mac',
                'ghi_chu' => 'Có việc gia đình',
                'nguoi_phe_duyet_id' => 2,
                'trang_thai_duyet' => 0,
                'ghi_chu_duyet' => null,
                'thoi_gian_phe_duyet' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nguoi_dung_id' => 4,
                'ngay_cham_cong' => '2024-03-01',
                'gio_vao' => null,
                'gio_ra' => null,
                'so_gio_lam' => 0,
                'so_cong' => 0,
                'gio_tang_ca' => 0,
                'phut_di_muon' => 0,
                'phut_ve_som' => 0,
                'trang_thai' => 'khong_cham_cong',
                'dia_chi_ip' => null,
                'ten_wifi' => null,
                'dia_chi_mac' => null,
                'ten_thiet_bi' => null,
                'phuong_thuc_cham_cong' => null,
                'ghi_chu' => 'Nghỉ phép',
                'nguoi_phe_duyet_id' => null,
                'trang_thai_duyet' => 1,
                'ghi_chu_duyet' => 'Đã nghỉ phép',
                'thoi_gian_phe_duyet' => '2024-03-01 08:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nguoi_dung_id' => 5,
                'ngay_cham_cong' => '2024-03-01',
                'gio_vao' => '08:30:00',
                'gio_ra' => '18:30:00',
                'so_gio_lam' => 9,
                'so_cong' => 1,
                'gio_tang_ca' => 1.5,
                'phut_di_muon' => 30,
                'phut_ve_som' => 0,
                'trang_thai' => 'di_muon',
                'dia_chi_ip' => '192.168.1.105',
                'ten_wifi' => 'Company_WiFi',
                'dia_chi_mac' => 'AA:BB:CC:DD:EE:05',
                'ten_thiet_bi' => 'PC-KeToan',
                'phuong_thuc_cham_cong' => 'manual',
                'ghi_chu' => 'Làm thêm giờ',
                'nguoi_phe_duyet_id' => 1,
                'trang_thai_duyet' => 1,
                'ghi_chu_duyet' => 'OK',
                'thoi_gian_phe_duyet' => '2024-03-01 19:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}