<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DonXinNghiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('don_xin_nghi')->insert([
            [
                'ma_don_nghi' => 'DN2024001',
                'nguoi_dung_id' => 2,
                'loai_nghi_phep_id' => 1,
                'ngay_bat_dau' => '2024-03-20',
                'ngay_ket_thuc' => '2024-03-22',
                'so_ngay_nghi' => 3,
                'ly_do' => 'Đi du lịch gia đình',
                'tai_lieu_ho_tro' => null,
                'lien_he_khan_cap' => 'Trần Văn A',
                'sdt_khan_cap' => '0912345679',
                'ban_giao_cho_id' => 3,
                'ghi_chu_ban_giao' => 'Đã bàn giao công việc cho Nguyễn Văn B',
                'trang_thai' => 'da_duyet',
                'cap_duyet_hien_tai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_don_nghi' => 'DN2024002',
                'nguoi_dung_id' => 3,
                'loai_nghi_phep_id' => 1,
                'ngay_bat_dau' => '2024-04-05',
                'ngay_ket_thuc' => '2024-04-07',
                'so_ngay_nghi' => 3,
                'ly_do' => 'Nghỉ lễ',
                'tai_lieu_ho_tro' => null,
                'lien_he_khan_cap' => 'Nguyễn Thị C',
                'sdt_khan_cap' => '0987654321',
                'ban_giao_cho_id' => 2,
                'ghi_chu_ban_giao' => 'Đã bàn giao đầy đủ',
                'trang_thai' => 'cho_duyet',
                'cap_duyet_hien_tai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_don_nghi' => 'DN2024003',
                'nguoi_dung_id' => 1,
                'loai_nghi_phep_id' => 2,
                'ngay_bat_dau' => '2024-03-10',
                'ngay_ket_thuc' => '2024-03-12',
                'so_ngay_nghi' => 3,
                'ly_do' => 'Bị ốm sốt cao',
                'tai_lieu_ho_tro' => json_encode(['giay_benh_vien.pdf']),
                'lien_he_khan_cap' => 'Nguyễn Văn D',
                'sdt_khan_cap' => '0912345680',
                'ban_giao_cho_id' => null,
                'ghi_chu_ban_giao' => null,
                'trang_thai' => 'da_duyet',
                'cap_duyet_hien_tai' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_don_nghi' => 'DN2024004',
                'nguoi_dung_id' => 4,
                'loai_nghi_phep_id' => 1,
                'ngay_bat_dau' => '2024-04-15',
                'ngay_ket_thuc' => '2024-04-20',
                'so_ngay_nghi' => 6,
                'ly_do' => 'Công việc gia đình',
                'tai_lieu_ho_tro' => null,
                'lien_he_khan_cap' => 'Phạm Thị E',
                'sdt_khan_cap' => '0987654322',
                'ban_giao_cho_id' => 5,
                'ghi_chu_ban_giao' => 'Đã bàn giao project cho Hoàng Văn F',
                'trang_thai' => 'tu_choi',
                'cap_duyet_hien_tai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_don_nghi' => 'DN2024005',
                'nguoi_dung_id' => 5,
                'loai_nghi_phep_id' => 4,
                'ngay_bat_dau' => '2024-05-01',
                'ngay_ket_thuc' => '2024-05-03',
                'so_ngay_nghi' => 3,
                'ly_do' => 'Việc riêng',
                'tai_lieu_ho_tro' => null,
                'lien_he_khan_cap' => 'Hoàng Thị G',
                'sdt_khan_cap' => '0912345681',
                'ban_giao_cho_id' => null,
                'ghi_chu_ban_giao' => null,
                'trang_thai' => 'cho_duyet',
                'cap_duyet_hien_tai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}