<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HopDongLaoDongSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('hop_dong_lao_dong')->insert([
            [
                'created_by' => 1,
                'nguoi_dung_id' => 1,
                'chuc_vu_id' => 1,
                'so_hop_dong' => 'HD001',
                'loai_hop_dong' => 'khong_xac_dinh',
                'ngay_bat_dau' => '2023-01-01',
                'ngay_ket_thuc' => null,
                'luong_co_ban' => 30000000,
                'phu_cap' => 5000000,
                'hinh_thuc_lam_viec' => 'Toàn thời gian',
                'dia_diem_lam_viec' => 'Văn phòng Hà Nội',
                'ghi_chu' => 'Hợp đồng chính thức',
                'ly_do_huy' => null,
                'duong_dan_file' => '/contracts/HD001.pdf',
                'file_dinh_kem' => null,
                'file_hop_dong_da_ky' => '/contracts/signed/HD001.pdf',
                'dieu_khoan' => 'Theo quy định công ty',
                'trang_thai_hop_dong' => 'da_ky',
                'trang_thai_ky' => 'da_ky',
                'trang_thai_tai_ky' => null,
                'nguoi_ky_id' => 1,
                'thoi_gian_ky' => '2023-01-01 10:00:00',
                'nguoi_huy_id' => null,
                'thoi_gian_huy' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_by' => 1,
                'nguoi_dung_id' => 2,
                'chuc_vu_id' => 2,
                'so_hop_dong' => 'HD002',
                'loai_hop_dong' => 'xac_dinh_thoi_han',
                'ngay_bat_dau' => '2023-06-01',
                'ngay_ket_thuc' => '2025-06-01',
                'luong_co_ban' => 20000000,
                'phu_cap' => 3000000,
                'hinh_thuc_lam_viec' => 'Toàn thời gian',
                'dia_diem_lam_viec' => 'Văn phòng TP.HCM',
                'ghi_chu' => 'Hợp đồng 2 năm',
                'ly_do_huy' => null,
                'duong_dan_file' => '/contracts/HD002.pdf',
                'file_dinh_kem' => null,
                'file_hop_dong_da_ky' => '/contracts/signed/HD002.pdf',
                'dieu_khoan' => 'Theo quy định công ty',
                'trang_thai_hop_dong' => 'da_ky',
                'trang_thai_ky' => 'da_ky',
                'trang_thai_tai_ky' => null,
                'nguoi_ky_id' => 1,
                'thoi_gian_ky' => '2023-06-01 14:30:00',
                'nguoi_huy_id' => null,
                'thoi_gian_huy' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_by' => 2,
                'nguoi_dung_id' => 3,
                'chuc_vu_id' => 3,
                'so_hop_dong' => 'HD003',
                'loai_hop_dong' => 'xac_dinh_thoi_han',
                'ngay_bat_dau' => '2024-01-15',
                'ngay_ket_thuc' => '2025-01-15',
                'luong_co_ban' => 10000000,
                'phu_cap' => 1000000,
                'hinh_thuc_lam_viec' => 'Toàn thời gian',
                'dia_diem_lam_viec' => 'Văn phòng Đà Nẵng',
                'ghi_chu' => 'Hợp đồng 1 năm',
                'ly_do_huy' => null,
                'duong_dan_file' => '/contracts/HD003.pdf',
                'file_dinh_kem' => null,
                'file_hop_dong_da_ky' => '/contracts/signed/HD003.pdf',
                'dieu_khoan' => 'Theo quy định công ty',
                'trang_thai_hop_dong' => 'da_ky',
                'trang_thai_ky' => 'da_ky',
                'trang_thai_tai_ky' => null,
                'nguoi_ky_id' => 2,
                'thoi_gian_ky' => '2024-01-15 09:00:00',
                'nguoi_huy_id' => null,
                'thoi_gian_huy' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_by' => 1,
                'nguoi_dung_id' => 4,
                'chuc_vu_id' => 3,
                'so_hop_dong' => 'HD004',
                'loai_hop_dong' => 'thoi_vu',
                'ngay_bat_dau' => '2024-03-01',
                'ngay_ket_thuc' => '2024-08-31',
                'luong_co_ban' => 8000000,
                'phu_cap' => 500000,
                'hinh_thuc_lam_viec' => 'Bán thời gian',
                'dia_diem_lam_viec' => 'Văn phòng Cần Thơ',
                'ghi_chu' => 'Hợp đồng thời vụ',
                'ly_do_huy' => null,
                'duong_dan_file' => '/contracts/HD004.pdf',
                'file_dinh_kem' => null,
                'file_hop_dong_da_ky' => '/contracts/signed/HD004.pdf',
                'dieu_khoan' => 'Theo quy định công ty',
                'trang_thai_hop_dong' => 'da_ky',
                'trang_thai_ky' => 'da_ky',
                'trang_thai_tai_ky' => null,
                'nguoi_ky_id' => 1,
                'thoi_gian_ky' => '2024-03-01 11:00:00',
                'nguoi_huy_id' => null,
                'thoi_gian_huy' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'created_by' => 2,
                'nguoi_dung_id' => 5,
                'chuc_vu_id' => 3,
                'so_hop_dong' => 'HD005',
                'loai_hop_dong' => 'xac_dinh_thoi_han',
                'ngay_bat_dau' => '2024-02-01',
                'ngay_ket_thuc' => '2026-02-01',
                'luong_co_ban' => 12000000,
                'phu_cap' => 1500000,
                'hinh_thuc_lam_viec' => 'Toàn thời gian',
                'dia_diem_lam_viec' => 'Văn phòng Bình Dương',
                'ghi_chu' => 'Hợp đồng 2 năm',
                'ly_do_huy' => null,
                'duong_dan_file' => '/contracts/HD005.pdf',
                'file_dinh_kem' => null,
                'file_hop_dong_da_ky' => '/contracts/signed/HD005.pdf',
                'dieu_khoan' => 'Theo quy định công ty',
                'trang_thai_hop_dong' => 'cho_ky',
                'trang_thai_ky' => 'chua_ky',
                'trang_thai_tai_ky' => null,
                'nguoi_ky_id' => null,
                'thoi_gian_ky' => null,
                'nguoi_huy_id' => null,
                'thoi_gian_huy' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}