<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HoSoNguoiDungSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('ho_so_nguoi_dung')->insert([
            [
                'nguoi_dung_id' => 1,
                'ma_nhan_vien' => 'NV001',
                'ho' => 'Nguyễn',
                'ten' => 'Văn A',
                'email_cong_ty' => 'nguyenvana@company.com',
                'so_dien_thoai' => '0912345678',
                'ngay_sinh' => '1985-05-10',
                'gioi_tinh' => 'nam',
                'dia_chi_hien_tai' => 'Số 10 Nguyễn Trãi, Hà Nội',
                'dia_chi_thuong_tru' => 'Số 10 Nguyễn Trãi, Hà Nội',
                'cmnd_cccd' => '001123456789',
                'so_ho_chieu' => null,
                'tinh_trang_hon_nhan' => 'da_ket_hon',
                'anh_dai_dien' => 'avatars/avatar1.jpg',
                'lien_he_khan_cap' => 'Nguyễn Thị B',
                'sdt_khan_cap' => '0987654321',
                'quan_he_khan_cap' => 'vợ',
                'anh_cccd_truoc' => 'cccd/truoc1.jpg',
                'anh_cccd_sau' => 'cccd/sau1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nguoi_dung_id' => 2,
                'ma_nhan_vien' => 'NV002',
                'ho' => 'Trần',
                'ten' => 'Văn B',
                'email_cong_ty' => 'tranvanb@company.com',
                'so_dien_thoai' => '0912345679',
                'ngay_sinh' => '1990-03-15',
                'gioi_tinh' => 'nam',
                'dia_chi_hien_tai' => 'Số 20 Lê Lợi, TP.HCM',
                'dia_chi_thuong_tru' => 'Số 20 Lê Lợi, TP.HCM',
                'cmnd_cccd' => '002123456789',
                'so_ho_chieu' => null,
                'tinh_trang_hon_nhan' => 'doc_than',
                'anh_dai_dien' => 'avatars/avatar2.jpg',
                'lien_he_khan_cap' => 'Trần Thị C',
                'sdt_khan_cap' => '0987654322',
                'quan_he_khan_cap' => 'mẹ',
                'anh_cccd_truoc' => 'cccd/truoc2.jpg',
                'anh_cccd_sau' => 'cccd/sau2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nguoi_dung_id' => 3,
                'ma_nhan_vien' => 'NV003',
                'ho' => 'Lê',
                'ten' => 'Thị D',
                'email_cong_ty' => 'lethid@company.com',
                'so_dien_thoai' => '0912345680',
                'ngay_sinh' => '1995-07-20',
                'gioi_tinh' => 'nu',
                'dia_chi_hien_tai' => 'Số 30 Hùng Vương, Đà Nẵng',
                'dia_chi_thuong_tru' => 'Số 30 Hùng Vương, Đà Nẵng',
                'cmnd_cccd' => '003123456789',
                'so_ho_chieu' => 'C1234567',
                'tinh_trang_hon_nhan' => 'doc_than',
                'anh_dai_dien' => 'avatars/avatar3.jpg',
                'lien_he_khan_cap' => 'Lê Văn E',
                'sdt_khan_cap' => '0987654323',
                'quan_he_khan_cap' => 'cha',
                'anh_cccd_truoc' => 'cccd/truoc3.jpg',
                'anh_cccd_sau' => 'cccd/sau3.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nguoi_dung_id' => 4,
                'ma_nhan_vien' => 'NV004',
                'ho' => 'Phạm',
                'ten' => 'Văn F',
                'email_cong_ty' => 'phamvanf@company.com',
                'so_dien_thoai' => '0912345681',
                'ngay_sinh' => '1988-11-25',
                'gioi_tinh' => 'nam',
                'dia_chi_hien_tai' => 'Số 40 Trần Hưng Đạo, Cần Thơ',
                'dia_chi_thuong_tru' => 'Số 40 Trần Hưng Đạo, Cần Thơ',
                'cmnd_cccd' => '004123456789',
                'so_ho_chieu' => null,
                'tinh_trang_hon_nhan' => 'da_ket_hon',
                'anh_dai_dien' => 'avatars/avatar4.jpg',
                'lien_he_khan_cap' => 'Phạm Thị G',
                'sdt_khan_cap' => '0987654324',
                'quan_he_khan_cap' => 'vợ',
                'anh_cccd_truoc' => 'cccd/truoc4.jpg',
                'anh_cccd_sau' => 'cccd/sau4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nguoi_dung_id' => 5,
                'ma_nhan_vien' => 'NV005',
                'ho' => 'Hoàng',
                'ten' => 'Thị H',
                'email_cong_ty' => 'hoangthih@company.com',
                'so_dien_thoai' => '0912345682',
                'ngay_sinh' => '1992-02-28',
                'gioi_tinh' => 'nu',
                'dia_chi_hien_tai' => 'Số 50 Lý Thường Kiệt, Bình Dương',
                'dia_chi_thuong_tru' => 'Số 50 Lý Thường Kiệt, Bình Dương',
                'cmnd_cccd' => '005123456789',
                'so_ho_chieu' => 'D1234567',
                'tinh_trang_hon_nhan' => 'doc_than',
                'anh_dai_dien' => 'avatars/avatar5.jpg',
                'lien_he_khan_cap' => 'Hoàng Văn I',
                'sdt_khan_cap' => '0987654325',
                'quan_he_khan_cap' => 'cha',
                'anh_cccd_truoc' => 'cccd/truoc5.jpg',
                'anh_cccd_sau' => 'cccd/sau5.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}