<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LoaiNghiPhepSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('loai_nghi_phep')->insert([
            [
                'ten' => 'Nghỉ phép năm',
                'ma' => 'PHEP_NAM',
                'mo_ta' => 'Nghỉ phép hàng năm',
                'so_ngay_nam' => 12,
                'toi_da_ngay_lien_tiep' => 30,
                'so_ngay_bao_truoc' => 1,
                'cho_phep_chuyen_nam' => 1,
                'toi_da_ngay_chuyen' => 5,
                'gioi_tinh_ap_dung' => 'tat_ca',
                'yeu_cau_giay_to' => 0,
                'co_luong' => 1,
                'trang_thai' => 1,
                'tinh_theo_ty_le' => 0,
                'nghi_che_do' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Nghỉ ốm',
                'ma' => 'OM',
                'mo_ta' => 'Nghỉ do ốm đau',
                'so_ngay_nam' => 30,
                'toi_da_ngay_lien_tiep' => 7,
                'so_ngay_bao_truoc' => 0,
                'cho_phep_chuyen_nam' => 0,
                'toi_da_ngay_chuyen' => 0,
                'gioi_tinh_ap_dung' => 'tat_ca',
                'yeu_cau_giay_to' => 1,
                'co_luong' => 1,
                'trang_thai' => 1,
                'tinh_theo_ty_le' => 0,
                'nghi_che_do' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Nghỉ thai sản',
                'ma' => 'THAI_SAN',
                'mo_ta' => 'Nghỉ thai sản',
                'so_ngay_nam' => 180,
                'toi_da_ngay_lien_tiep' => 180,
                'so_ngay_bao_truoc' => 30,
                'cho_phep_chuyen_nam' => 0,
                'toi_da_ngay_chuyen' => 0,
                'gioi_tinh_ap_dung' => 'nu',
                'yeu_cau_giay_to' => 1,
                'co_luong' => 1,
                'trang_thai' => 1,
                'tinh_theo_ty_le' => 0,
                'nghi_che_do' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Nghỉ không lương',
                'ma' => 'KHONG_LUONG',
                'mo_ta' => 'Nghỉ không hưởng lương',
                'so_ngay_nam' => 30,
                'toi_da_ngay_lien_tiep' => 10,
                'so_ngay_bao_truoc' => 3,
                'cho_phep_chuyen_nam' => 0,
                'toi_da_ngay_chuyen' => 0,
                'gioi_tinh_ap_dung' => 'tat_ca',
                'yeu_cau_giay_to' => 0,
                'co_luong' => 0,
                'trang_thai' => 1,
                'tinh_theo_ty_le' => 0,
                'nghi_che_do' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Nghỉ lễ',
                'ma' => 'LE',
                'mo_ta' => 'Nghỉ lễ theo quy định',
                'so_ngay_nam' => 11,
                'toi_da_ngay_lien_tiep' => 9,
                'so_ngay_bao_truoc' => 0,
                'cho_phep_chuyen_nam' => 0,
                'toi_da_ngay_chuyen' => 0,
                'gioi_tinh_ap_dung' => 'tat_ca',
                'yeu_cau_giay_to' => 0,
                'co_luong' => 1,
                'trang_thai' => 1,
                'tinh_theo_ty_le' => 0,
                'nghi_che_do' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}