<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LuongNhanVienSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('luong_nhan_vien')->insert([
            [
                'bang_luong_id' => 1,
                'luong_thang' => 1,
                'luong_nam' => 2024,
                'nguoi_dung_id' => 1,
                'luong_co_ban' => 30000000,
                'tong_phu_cap' => 3000000,
                'tong_khau_tru' => 3000000,
                'tong_luong' => 30000000,
                'luong_thuc_nhan' => 27000000,
                'so_ngay_cong' => 22,
                'gio_tang_ca' => 10,
                'cong_tang_ca' => 1.5,
                'ngay_nghi_phep' => 0,
                'ngay_nghi_khong_phep' => 0,
                'ngay_le' => 0,
                'thue_thu_nhap_ca_nhan' => 3000000,
                'ghi_chu' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bang_luong_id' => 1,
                'luong_thang' => 1,
                'luong_nam' => 2024,
                'nguoi_dung_id' => 2,
                'luong_co_ban' => 20000000,
                'tong_phu_cap' => 1500000,
                'tong_khau_tru' => 2150000,
                'tong_luong' => 21500000,
                'luong_thuc_nhan' => 19350000,
                'so_ngay_cong' => 20,
                'gio_tang_ca' => 0,
                'cong_tang_ca' => 0,
                'ngay_nghi_phep' => 2,
                'ngay_nghi_khong_phep' => 0,
                'ngay_le' => 0,
                'thue_thu_nhap_ca_nhan' => 2150000,
                'ghi_chu' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bang_luong_id' => 1,
                'luong_thang' => 1,
                'luong_nam' => 2024,
                'nguoi_dung_id' => 3,
                'luong_co_ban' => 10000000,
                'tong_phu_cap' => 500000,
                'tong_khau_tru' => 1050000,
                'tong_luong' => 10500000,
                'luong_thuc_nhan' => 9450000,
                'so_ngay_cong' => 22,
                'gio_tang_ca' => 5,
                'cong_tang_ca' => 0.75,
                'ngay_nghi_phep' => 0,
                'ngay_nghi_khong_phep' => 0,
                'ngay_le' => 0,
                'thue_thu_nhap_ca_nhan' => 1050000,
                'ghi_chu' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bang_luong_id' => 2,
                'luong_thang' => 2,
                'luong_nam' => 2024,
                'nguoi_dung_id' => 1,
                'luong_co_ban' => 30000000,
                'tong_phu_cap' => 3000000,
                'tong_khau_tru' => 3000000,
                'tong_luong' => 30000000,
                'luong_thuc_nhan' => 27000000,
                'so_ngay_cong' => 20,
                'gio_tang_ca' => 15,
                'cong_tang_ca' => 2.25,
                'ngay_nghi_phep' => 2,
                'ngay_nghi_khong_phep' => 0,
                'ngay_le' => 0,
                'thue_thu_nhap_ca_nhan' => 3000000,
                'ghi_chu' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bang_luong_id' => 2,
                'luong_thang' => 2,
                'luong_nam' => 2024,
                'nguoi_dung_id' => 4,
                'luong_co_ban' => 8000000,
                'tong_phu_cap' => 800000,
                'tong_khau_tru' => 880000,
                'tong_luong' => 8800000,
                'luong_thuc_nhan' => 7920000,
                'so_ngay_cong' => 21,
                'gio_tang_ca' => 0,
                'cong_tang_ca' => 0,
                'ngay_nghi_phep' => 1,
                'ngay_nghi_khong_phep' => 0,
                'ngay_le' => 0,
                'thue_thu_nhap_ca_nhan' => 880000,
                'ghi_chu' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}