<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TinTuyenDungSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tin_tuyen_dung')->insert([
            [
                'tieu_de' => 'Tuyển dụng Lập trình viên PHP',
                'ma' => 'TD001',
                'phong_ban_id' => 2,
                'chuc_vu_id' => 3,
                'vai_tro_id' => 4,
                'loai_hop_dong' => 'khong_xac_dinh',
                'cap_do_kinh_nghiem' => 'senior',
                'kinh_nghiem_toi_thieu' => 3,
                'kinh_nghiem_toi_da' => 5,
                'luong_toi_thieu' => 15000000,
                'luong_toi_da' => 25000000,
                'so_vi_tri' => 3,
                'mo_ta_cong_viec' => 'Phát triển web bằng PHP/Laravel. Yêu cầu có kinh nghiệm 3+ năm.',
                'yeu_cau' => json_encode(['PHP', 'Laravel', 'MySQL']),
                'phuc_loi' => json_encode(['BHXH', 'Thưởng Tết', 'Du lịch hàng năm']),
                'ky_nang_yeu_cau' => json_encode(['Giao tiếp tốt', 'Làm việc nhóm']),
                'trinh_do_hoc_van' => 'Đại học',
                'han_nop_ho_so' => '2024-04-30',
                'lam_viec_tu_xa' => 0,
                'tuyen_gap' => 1,
                'trang_thai' => 'dang_dang',
                'nguoi_dang_id' => 1,
                'thoi_gian_dang' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Tuyển dụng Nhân viên Kinh doanh',
                'ma' => 'TD002',
                'phong_ban_id' => 3,
                'chuc_vu_id' => 3,
                'vai_tro_id' => 4,
                'loai_hop_dong' => 'xac_dinh_thoi_han',
                'cap_do_kinh_nghiem' => 'junior',
                'kinh_nghiem_toi_thieu' => 1,
                'kinh_nghiem_toi_da' => 2,
                'luong_toi_thieu' => 8000000,
                'luong_toi_da' => 12000000,
                'so_vi_tri' => 5,
                'mo_ta_cong_viec' => 'Tìm kiếm khách hàng, chăm sóc khách hàng',
                'yeu_cau' => json_encode(['Kỹ năng bán hàng', 'Giao tiếp tốt']),
                'phuc_loi' => json_encode(['Hoa hồng', 'Thưởng doanh số']),
                'ky_nang_yeu_cau' => json_encode(['Thuyết phục', 'Đàm phán']),
                'trinh_do_hoc_van' => 'Cao đẳng trở lên',
                'han_nop_ho_so' => '2024-05-15',
                'lam_viec_tu_xa' => 0,
                'tuyen_gap' => 1,
                'trang_thai' => 'dang_dang',
                'nguoi_dang_id' => 1,
                'thoi_gian_dang' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Tuyển dụng Kế toán tổng hợp',
                'ma' => 'TD003',
                'phong_ban_id' => 4,
                'chuc_vu_id' => 3,
                'vai_tro_id' => 5,
                'loai_hop_dong' => 'khong_xac_dinh',
                'cap_do_kinh_nghiem' => 'senior',
                'kinh_nghiem_toi_thieu' => 3,
                'kinh_nghiem_toi_da' => 7,
                'luong_toi_thieu' => 12000000,
                'luong_toi_da' => 18000000,
                'so_vi_tri' => 2,
                'mo_ta_cong_viec' => 'Quản lý sổ sách kế toán, báo cáo thuế',
                'yeu_cau' => json_encode(['Kế toán', 'Thuế', 'Phần mềm kế toán']),
                'phuc_loi' => json_encode(['BHXH', 'Thưởng năm']),
                'ky_nang_yeu_cau' => json_encode(['Tỉ mỉ', 'Chính xác']),
                'trinh_do_hoc_van' => 'Đại học chuyên ngành Kế toán',
                'han_nop_ho_so' => '2024-05-10',
                'lam_viec_tu_xa' => 0,
                'tuyen_gap' => 0,
                'trang_thai' => 'dang_dang',
                'nguoi_dang_id' => 1,
                'thoi_gian_dang' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Tuyển dụng Marketing Executive',
                'ma' => 'TD004',
                'phong_ban_id' => 5,
                'chuc_vu_id' => 3,
                'vai_tro_id' => 4,
                'loai_hop_dong' => 'xac_dinh_thoi_han',
                'cap_do_kinh_nghiem' => 'junior',
                'kinh_nghiem_toi_thieu' => 1,
                'kinh_nghiem_toi_da' => 3,
                'luong_toi_thieu' => 10000000,
                'luong_toi_da' => 15000000,
                'so_vi_tri' => 2,
                'mo_ta_cong_viec' => 'Lên kế hoạch marketing, quảng cáo online',
                'yeu_cau' => json_encode(['SEO', 'Facebook Ads', 'Content']),
                'phuc_loi' => json_encode(['BHXH', 'Thưởng']),
                'ky_nang_yeu_cau' => json_encode(['Sáng tạo', 'Phân tích']),
                'trinh_do_hoc_van' => 'Đại học Marketing',
                'han_nop_ho_so' => '2024-04-25',
                'lam_viec_tu_xa' => 1,
                'tuyen_gap' => 1,
                'trang_thai' => 'da_dong',
                'nguoi_dang_id' => 1,
                'thoi_gian_dang' => '2024-03-01 10:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Tuyển dụng Thực tập sinh IT',
                'ma' => 'TD005',
                'phong_ban_id' => 2,
                'chuc_vu_id' => 5,
                'vai_tro_id' => 4,
                'loai_hop_dong' => 'thoi_vu',
                'cap_do_kinh_nghiem' => 'thuc_tap',
                'kinh_nghiem_toi_thieu' => 0,
                'kinh_nghiem_toi_da' => 0,
                'luong_toi_thieu' => 3000000,
                'luong_toi_da' => 5000000,
                'so_vi_tri' => 4,
                'mo_ta_cong_viec' => 'Hỗ trợ lập trình viên, học tập và phát triển',
                'yeu_cau' => json_encode(['HTML', 'CSS', 'JavaScript cơ bản']),
                'phuc_loi' => json_encode(['Được đào tạo', 'Cơ hội lên nhân viên chính thức']),
                'ky_nang_yeu_cau' => json_encode(['Cầu thị', 'Chịu khó học hỏi']),
                'trinh_do_hoc_van' => 'Đang học năm cuối hoặc mới ra trường',
                'han_nop_ho_so' => '2024-06-30',
                'lam_viec_tu_xa' => 0,
                'tuyen_gap' => 0,
                'trang_thai' => 'dang_dang',
                'nguoi_dang_id' => 1,
                'thoi_gian_dang' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}