<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UngTuyenSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('ung_tuyen')->insert([
            [
                'ma_ung_tuyen' => 'UT001',
                'tin_tuyen_dung_id' => 1,
                'ten_ung_vien' => 'Nguyễn Văn A',
                'email' => 'nguyenvana@email.com',
                'so_dien_thoai' => '0912345001',
                'kinh_nghiem' => '4 năm PHP',
                'ky_nang' => 'PHP, Laravel, MySQL',
                'thu_gioi_thieu' => 'Tôi mong muốn được làm việc tại công ty',
                'tai_cv' => '/cvs/nguyenvana.pdf',
                'diem_danh_gia' => 85,
                'trang_thai_pv' => 'da',
                'diem_phong_van' => 85,
                'ghi_chu' => 'Phù hợp',
                'trang_thai' => 'dang_xu_ly',
                'trang_thai_email' => 'da_gui',
                'trang_thai_email_trungtuyen' => 'chua_gui',
                'ly_do' => null,
                'ngay_cap_nhat' => now(),
                'nguoi_cap_nhat' => 2,
                'nguoi_cap_nhat_id' => 2,
                'nguoi_cap_nhat_cuoi_id' => 2,
                'vai_tro_id' => 4,
                'phong_ban_id' => 2,
                'chuc_vu_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_ung_tuyen' => 'UT002',
                'tin_tuyen_dung_id' => 2,
                'ten_ung_vien' => 'Lê Văn C',
                'email' => 'levanc@email.com',
                'so_dien_thoai' => '0912345003',
                'kinh_nghiem' => '5 năm kinh doanh',
                'ky_nang' => 'Bán hàng, CSKH',
                'thu_gioi_thieu' => 'Tôi có nhiều kinh nghiệm bán hàng',
                'tai_cv' => '/cvs/levanc.pdf',
                'diem_danh_gia' => 90,
                'trang_thai_pv' => 'da',
                'diem_phong_van' => 90,
                'ghi_chu' => 'Rất tốt',
                'trang_thai' => 'trung_tuyen',
                'trang_thai_email' => 'da_gui',
                'trang_thai_email_trungtuyen' => 'da_gui',
                'ly_do' => null,
                'ngay_cap_nhat' => now(),
                'nguoi_cap_nhat' => 3,
                'nguoi_cap_nhat_id' => 3,
                'nguoi_cap_nhat_cuoi_id' => 3,
                'vai_tro_id' => 4,
                'phong_ban_id' => 3,
                'chuc_vu_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_ung_tuyen' => 'UT003',
                'tin_tuyen_dung_id' => 3,
                'ten_ung_vien' => 'Phạm Thị D',
                'email' => 'phamthid@email.com',
                'so_dien_thoai' => '0912345004',
                'kinh_nghiem' => '4 năm kế toán',
                'ky_nang' => 'Kế toán, Thuế',
                'thu_gioi_thieu' => 'Tôi đã làm kế toán 4 năm',
                'tai_cv' => '/cvs/phamthid.pdf',
                'diem_danh_gia' => 65,
                'trang_thai_pv' => 'da',
                'diem_phong_van' => 65,
                'ghi_chu' => 'Cần cải thiện',
                'trang_thai' => 'tu_choi',
                'trang_thai_email' => 'da_gui',
                'trang_thai_email_trungtuyen' => 'chua_gui',
                'ly_do' => 'Chưa đáp ứng yêu cầu',
                'ngay_cap_nhat' => now(),
                'nguoi_cap_nhat' => 5,
                'nguoi_cap_nhat_id' => 5,
                'nguoi_cap_nhat_cuoi_id' => 5,
                'vai_tro_id' => 5,
                'phong_ban_id' => 4,
                'chuc_vu_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_ung_tuyen' => 'UT004',
                'tin_tuyen_dung_id' => 4,
                'ten_ung_vien' => 'Trần Thị B',
                'email' => 'tranthib@email.com',
                'so_dien_thoai' => '0912345002',
                'kinh_nghiem' => '3 năm Marketing',
                'ky_nang' => 'SEO, Facebook Ads',
                'thu_gioi_thieu' => 'Tôi am hiểu về digital marketing',
                'tai_cv' => '/cvs/tranthib.pdf',
                'diem_danh_gia' => 80,
                'trang_thai_pv' => 'chua',
                'diem_phong_van' => null,
                'ghi_chu' => null,
                'trang_thai' => 'moi',
                'trang_thai_email' => 'da_gui',
                'trang_thai_email_trungtuyen' => 'chua_gui',
                'ly_do' => null,
                'ngay_cap_nhat' => now(),
                'nguoi_cap_nhat' => null,
                'nguoi_cap_nhat_id' => null,
                'nguoi_cap_nhat_cuoi_id' => null,
                'vai_tro_id' => 4,
                'phong_ban_id' => 5,
                'chuc_vu_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_ung_tuyen' => 'UT005',
                'tin_tuyen_dung_id' => 5,
                'ten_ung_vien' => 'Hoàng Văn E',
                'email' => 'hoangvane@email.com',
                'so_dien_thoai' => '0912345005',
                'kinh_nghiem' => 'Mới ra trường',
                'ky_nang' => 'HTML, CSS, JS',
                'thu_gioi_thieu' => 'Em muốn học hỏi kinh nghiệm',
                'tai_cv' => '/cvs/hoangvane.pdf',
                'diem_danh_gia' => null,
                'trang_thai_pv' => 'chua',
                'diem_phong_van' => null,
                'ghi_chu' => null,
                'trang_thai' => 'moi',
                'trang_thai_email' => 'chua_gui',
                'trang_thai_email_trungtuyen' => 'chua_gui',
                'ly_do' => null,
                'ngay_cap_nhat' => null,
                'nguoi_cap_nhat' => null,
                'nguoi_cap_nhat_id' => null,
                'nguoi_cap_nhat_cuoi_id' => null,
                'vai_tro_id' => 4,
                'phong_ban_id' => 2,
                'chuc_vu_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}