<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UngVienSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('ung_vien')->insert([
            [
                'tin_tuyen_dung_id' => 1,
                'ma_ho_so' => 'UV001',
                'ho' => 'Nguyễn',
                'ten' => 'Văn A',
                'email' => 'nguyenvana@email.com',
                'so_dien_thoai' => '0912345001',
                'dia_chi' => 'Hà Nội',
                'ngay_sinh' => '1995-05-10',
                'gioi_tinh' => 'nam',
                'trinh_do_hoc_van' => 'Đại học Bách Khoa Hà Nội',
                'so_nam_kinh_nghiem' => 4,
                'luong_hien_tai' => 15000000,
                'luong_mong_muon' => 20000000,
                'duong_dan_cv' => '/cvs/nguyenvana.pdf',
                'thu_xin_viec' => 'Tôi rất mong muốn được làm việc tại công ty',
                'url_portfolio' => 'https://github.com/nguyenvana',
                'url_linkedin' => 'https://linkedin.com/in/nguyenvana',
                'ky_nang' => json_encode(['PHP', 'Laravel', 'MySQL']),
                'ngay_co_the_lam_viec' => '2024-05-01',
                'nguon_ung_tuyen' => 'linkedin',
                'ten_nguoi_gioi_thieu' => null,
                'trang_thai' => 'da_phong_van',
                'diem_phong_van' => 85,
                'ghi_chu_phong_van' => 'Có kinh nghiệm phù hợp',
                'ly_do_tu_choi' => null,
                'nguoi_dung_id' => 2,
                'thoi_gian_nop' => '2024-03-15 09:00:00',
                'nguoi_cap_nhat_cuoi_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tin_tuyen_dung_id' => 1,
                'ma_ho_so' => 'UV002',
                'ho' => 'Trần',
                'ten' => 'Thị B',
                'email' => 'tranthib@email.com',
                'so_dien_thoai' => '0912345002',
                'dia_chi' => 'TP.HCM',
                'ngay_sinh' => '1997-08-15',
                'gioi_tinh' => 'nu',
                'trinh_do_hoc_van' => 'Đại học Khoa học Tự nhiên',
                'so_nam_kinh_nghiem' => 3,
                'luong_hien_tai' => 12000000,
                'luong_mong_muon' => 18000000,
                'duong_dan_cv' => '/cvs/tranthib.pdf',
                'thu_xin_viec' => 'Tôi mong muốn được đóng góp cho công ty',
                'url_portfolio' => 'https://github.com/tranthib',
                'url_linkedin' => null,
                'ky_nang' => json_encode(['PHP', 'React', 'PostgreSQL']),
                'ngay_co_the_lam_viec' => '2024-05-15',
                'nguon_ung_tuyen' => 'web',
                'ten_nguoi_gioi_thieu' => null,
                'trang_thai' => 'cho_phong_van',
                'diem_phong_van' => null,
                'ghi_chu_phong_van' => null,
                'ly_do_tu_choi' => null,
                'nguoi_dung_id' => null,
                'thoi_gian_nop' => '2024-03-20 14:30:00',
                'nguoi_cap_nhat_cuoi_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tin_tuyen_dung_id' => 2,
                'ma_ho_so' => 'UV003',
                'ho' => 'Lê',
                'ten' => 'Văn C',
                'email' => 'levanc@email.com',
                'so_dien_thoai' => '0912345003',
                'dia_chi' => 'Đà Nẵng',
                'ngay_sinh' => '1993-12-20',
                'gioi_tinh' => 'nam',
                'trinh_do_hoc_van' => 'Đại học Kinh tế',
                'so_nam_kinh_nghiem' => 5,
                'luong_hien_tai' => 10000000,
                'luong_mong_muon' => 15000000,
                'duong_dan_cv' => '/cvs/levanc.pdf',
                'thu_xin_viec' => 'Tôi tự tin với khả năng kinh doanh của mình',
                'url_portfolio' => null,
                'url_linkedin' => 'https://linkedin.com/in/levanc',
                'ky_nang' => json_encode(['Bán hàng', 'Chăm sóc khách hàng', 'Đàm phán']),
                'ngay_co_the_lam_viec' => '2024-04-20',
                'nguon_ung_tuyen' => 'facebook',
                'ten_nguoi_gioi_thieu' => 'Nguyễn Văn D',
                'trang_thai' => 'trung_tuyen',
                'diem_phong_van' => 90,
                'ghi_chu_phong_van' => 'Rất phù hợp với vị trí',
                'ly_do_tu_choi' => null,
                'nguoi_dung_id' => 3,
                'thoi_gian_nop' => '2024-03-10 11:15:00',
                'nguoi_cap_nhat_cuoi_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tin_tuyen_dung_id' => 3,
                'ma_ho_so' => 'UV004',
                'ho' => 'Phạm',
                'ten' => 'Thị D',
                'email' => 'phamthid@email.com',
                'so_dien_thoai' => '0912345004',
                'dia_chi' => 'Cần Thơ',
                'ngay_sinh' => '1994-03-25',
                'gioi_tinh' => 'nu',
                'trinh_do_hoc_van' => 'Đại học Tài chính Kế toán',
                'so_nam_kinh_nghiem' => 4,
                'luong_hien_tai' => 10000000,
                'luong_mong_muon' => 14000000,
                'duong_dan_cv' => '/cvs/phamthid.pdf',
                'thu_xin_viec' => 'Tôi có kinh nghiệm 4 năm trong lĩnh vực kế toán',
                'url_portfolio' => null,
                'url_linkedin' => null,
                'ky_nang' => json_encode(['Kế toán', 'Thuế', 'Excel']),
                'ngay_co_the_lam_viec' => '2024-05-01',
                'nguon_ung_tuyen' => 'web',
                'ten_nguoi_gioi_thieu' => null,
                'trang_thai' => 'tu_choi',
                'diem_phong_van' => 65,
                'ghi_chu_phong_van' => 'Chưa đáp ứng yêu cầu',
                'ly_do_tu_choi' => 'Thiếu kinh nghiệm phần mềm kế toán MISA',
                'nguoi_dung_id' => 5,
                'thoi_gian_nop' => '2024-03-18 16:00:00',
                'nguoi_cap_nhat_cuoi_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tin_tuyen_dung_id' => 5,
                'ma_ho_so' => 'UV005',
                'ho' => 'Hoàng',
                'ten' => 'Văn E',
                'email' => 'hoangvane@email.com',
                'so_dien_thoai' => '0912345005',
                'dia_chi' => 'Bình Dương',
                'ngay_sinh' => '2000-07-10',
                'gioi_tinh' => 'nam',
                'trinh_do_hoc_van' => 'Cao đẳng FPT',
                'so_nam_kinh_nghiem' => 0,
                'luong_hien_tai' => null,
                'luong_mong_muon' => 5000000,
                'duong_dan_cv' => '/cvs/hoangvane.pdf',
                'thu_xin_viec' => 'Em mong muốn được học hỏi và phát triển',
                'url_portfolio' => 'https://github.com/hoangvane',
                'url_linkedin' => null,
                'ky_nang' => json_encode(['HTML', 'CSS', 'JavaScript cơ bản']),
                'ngay_co_the_lam_viec' => '2024-06-01',
                'nguon_ung_tuyen' => 'linkedin',
                'ten_nguoi_gioi_thieu' => null,
                'trang_thai' => 'moi_nop',
                'diem_phong_van' => null,
                'ghi_chu_phong_van' => null,
                'ly_do_tu_choi' => null,
                'nguoi_dung_id' => null,
                'thoi_gian_nop' => '2024-04-01 08:30:00',
                'nguoi_cap_nhat_cuoi_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}