<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class YeuCauTuyenDungSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('yeu_cau_tuyen_dung')->insert([
            [
                'ma' => 'YCTD001',
                'nguoi_tao_id' => 2,
                'phong_ban_id' => 2,
                'chuc_vu_id' => 3,
                'so_luong' => 2,
                'loai_hop_dong' => 'khong_xac_dinh',
                'luong_toi_thieu' => 15000000,
                'luong_toi_da' => 20000000,
                'trinh_do_hoc_van' => 'Đại học',
                'kinh_nghiem_toi_thieu' => 2,
                'kinh_nghiem_toi_da' => 4,
                'mo_ta_cong_viec' => 'Tìm kiếm lập trình viên PHP có kinh nghiệm',
                'yeu_cau' => 'Thành thạo PHP, Laravel, MySQL',
                'ky_nang_yeu_cau' => json_encode(['PHP', 'Laravel', 'MySQL']),
                'ghi_chu' => 'Cần tuyển gấp',
                'trang_thai' => 'da_duyet',
                'trang_thai_dang' => 'da_dang',
                'nguoi_duyet_id' => 1,
                'thoi_gian_duyet' => '2024-02-20 10:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma' => 'YCTD002',
                'nguoi_tao_id' => 3,
                'phong_ban_id' => 3,
                'chuc_vu_id' => 3,
                'so_luong' => 3,
                'loai_hop_dong' => 'xac_dinh_thoi_han',
                'luong_toi_thieu' => 8000000,
                'luong_toi_da' => 12000000,
                'trinh_do_hoc_van' => 'Cao đẳng',
                'kinh_nghiem_toi_thieu' => 1,
                'kinh_nghiem_toi_da' => 3,
                'mo_ta_cong_viec' => 'Tuyển nhân viên kinh doanh',
                'yeu_cau' => 'Có kỹ năng giao tiếp tốt',
                'ky_nang_yeu_cau' => json_encode(['Giao tiếp', 'Bán hàng']),
                'ghi_chu' => null,
                'trang_thai' => 'da_duyet',
                'trang_thai_dang' => 'da_dang',
                'nguoi_duyet_id' => 1,
                'thoi_gian_duyet' => '2024-02-25 14:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma' => 'YCTD003',
                'nguoi_tao_id' => 5,
                'phong_ban_id' => 4,
                'chuc_vu_id' => 3,
                'so_luong' => 1,
                'loai_hop_dong' => 'khong_xac_dinh',
                'luong_toi_thieu' => 12000000,
                'luong_toi_da' => 15000000,
                'trinh_do_hoc_van' => 'Đại học',
                'kinh_nghiem_toi_thieu' => 3,
                'kinh_nghiem_toi_da' => 5,
                'mo_ta_cong_viec' => 'Tuyển kế toán tổng hợp',
                'yeu_cau' => 'Có kinh nghiệm làm báo cáo thuế',
                'ky_nang_yeu_cau' => json_encode(['Kế toán', 'Thuế', 'MISA']),
                'ghi_chu' => null,
                'trang_thai' => 'cho_duyet',
                'trang_thai_dang' => 'chua_dang',
                'nguoi_duyet_id' => null,
                'thoi_gian_duyet' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma' => 'YCTD004',
                'nguoi_tao_id' => 1,
                'phong_ban_id' => 5,
                'chuc_vu_id' => 3,
                'so_luong' => 2,
                'loai_hop_dong' => 'xac_dinh_thoi_han',
                'luong_toi_thieu' => 10000000,
                'luong_toi_da' => 14000000,
                'trinh_do_hoc_van' => 'Đại học',
                'kinh_nghiem_toi_thieu' => 2,
                'kinh_nghiem_toi_da' => 4,
                'mo_ta_cong_viec' => 'Tuyển nhân viên Marketing',
                'yeu_cau' => 'Có kinh nghiệm chạy ads',
                'ky_nang_yeu_cau' => json_encode(['Facebook Ads', 'Google Ads', 'SEO']),
                'ghi_chu' => 'Cần tuyển ngay',
                'trang_thai' => 'da_duyet',
                'trang_thai_dang' => 'da_dang',
                'nguoi_duyet_id' => 1,
                'thoi_gian_duyet' => '2024-03-01 09:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma' => 'YCTD005',
                'nguoi_tao_id' => 2,
                'phong_ban_id' => 2,
                'chuc_vu_id' => 5,
                'so_luong' => 3,
                'loai_hop_dong' => 'thoi_vu',
                'luong_toi_thieu' => 3000000,
                'luong_toi_da' => 5000000,
                'trinh_do_hoc_van' => 'Đang học năm cuối',
                'kinh_nghiem_toi_thieu' => 0,
                'kinh_nghiem_toi_da' => 0,
                'mo_ta_cong_viec' => 'Tuyển thực tập sinh IT',
                'yeu_cau' => 'Có kiến thức cơ bản về lập trình',
                'ky_nang_yeu_cau' => json_encode(['HTML', 'CSS', 'JavaScript']),
                'ghi_chu' => null,
                'trang_thai' => 'tu_choi',
                'trang_thai_dang' => 'chua_dang',
                'nguoi_duyet_id' => 1,
                'thoi_gian_duyet' => '2024-03-05 11:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}